r"""make_bibtest.py -- generate the bibtex driver from the manuscript's own citations.

bibtest.tex existed to run medphy.bst over the .bib, but it carried a key list typed by
hand. That is the same defect that let \cite{nnunet} and \cite{ribseg} print "[?]" for a
year: a hand-maintained list drifts from the text it is supposed to mirror. The list is now
read out of main.tex, so it cannot drift.

Order matters as much as membership. The reference list is pasted into the manuscript as a
numbered thebibliography, so an entry's number is its position in that list, and the
guidelines require references numbered in order of first appearance. Keys are therefore
emitted in order of first citation in main.tex, and the driver passes them to natbib
unsorted -- sorting here would renumber the manuscript.

The whole chain is:
    python make_bibtest.py && pdflatex bibtest && bibtex bibtest && python inline_bbl.py
"""
from pathlib import Path
import re

HERE = Path(__file__).parent
main = (HERE / "main.tex").read_text(encoding="utf-8")

# strip comments first: a commented-out \cite must not claim a reference number
live = "\n".join(re.sub(r"(?<!\\)%.*$", "", ln) for ln in main.split("\n"))

# first-citation order, de-duplicated
keys, seen = [], set()
for m in re.finditer(r"\\cite\{([^}]*)\}", live):
    for k in (k.strip() for k in m.group(1).split(",")):
        if k and k not in seen:
            seen.add(k)
            keys.append(k)

defined = set(re.findall(r"^@\w+\{([^,]+),", (HERE / "ctspinopelvic1k.bib").read_text(encoding="utf-8"), re.M))
missing = [k for k in keys if k not in defined]
unused = sorted(defined - seen)
if missing:
    raise SystemExit(f"cited but absent from the .bib: {missing}")

body = ",\n".join(",".join(keys[i:i + 4]) for i in range(0, len(keys), 4))
(HERE / "bibtest.tex").write_text(
    "% GENERATED by make_bibtest.py -- do not hand-edit; the key list is read from main.tex.\n"
    "% Unsorted and in order of first citation, because the .bbl order sets the printed\n"
    "% reference numbers when it is pasted into the manuscript.\n"
    "\\documentclass[12pt]{article}\n"
    "\\usepackage[super,comma]{natbib}\n"
    "\\begin{document}\n"
    "Every reference cited by main.tex: \\cite{" + body + "}.\n"
    "\\bibliographystyle{./medphy}\n"
    "\\bibliography{./ctspinopelvic1k}\n"
    "\\end{document}\n", encoding="utf-8")

print(f"bibtest.tex: {len(keys)} keys in first-citation order")
if unused:
    print(f"in the .bib but never cited (will not be printed): {unused}")
