r"""paper/mpda/make_submission.py -- the upload set for the journal's submission form.

The form wants: the manuscript with figures embedded and captions beneath them AND a list of
figure captions after the references; each figure as its own numbered file; the title page
as a separate item; supporting information separately. This script:

  1. writes figure_captions.tex from the \caption{} of every figure in main.tex, in order,
     which main.tex \input{}s after the bibliography when \captionlisttrue (the preprint;
     the ten-page typeset check sets it false so captions are not counted twice);
  2. exports Fig. 1 (drawn in TikZ inside main.tex) as a standalone PDF;
  3. assembles dist/submission/ with the files named as the form expects.

    python paper/mpda/make_submission.py        (after the PDFs are built)
"""
from __future__ import annotations

import re
import shutil
import subprocess
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
src = (HERE / "main.tex").read_text(encoding="utf-8")

# ---- 1. caption list -------------------------------------------------------------------
figs = []
for m in re.finditer(r"\\begin\{figure\*?\}(.*?)\\end\{figure\*?\}", src, re.S):
    body = m.group(1)
    c = re.search(r"\\caption\{", body)
    if not c:
        continue
    # balanced-brace extraction of the caption argument
    i = c.end(); depth = 1
    while depth:
        ch = body[i]; depth += (ch == "{") - (ch == "}"); i += 1
    cap = body[c.end():i - 1]
    cap = re.sub(r"\\label\{[^}]*\}", "", cap).strip()
    figs.append(re.sub(r"\s+", " ", cap))
lines = ["\\section*{Figure captions}", "% generated by make_submission.py; do not edit by hand"]
for k, cap in enumerate(figs, 1):
    lines.append(f"\\noindent\\textbf{{Figure {k}.}} {cap}\n")
(HERE / "figure_captions.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"figure_captions.tex: {len(figs)} captions")

# ---- 2. Fig. 1 standalone ---------------------------------------------------------------
tikz = re.search(r"(\\begin\{tikzpicture\}\[\n  % absolute 8 pt.*?\\end\{tikzpicture\})", src, re.S)
if not tikz:
    tikz = re.search(r"(\\begin\{tikzpicture\}\[.*?\\end\{tikzpicture\})", src, re.S)
standalone = r"""\documentclass[border=2pt]{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows.meta, positioning, fit, backgrounds, calc}
\begin{document}
\linespread{1}\selectfont
""" + tikz.group(1) + "\n\\end{document}\n"
(HERE / "fig_pipeline_standalone.tex").write_text(standalone, encoding="utf-8")
print("fig_pipeline_standalone.tex written (compile with pdflatex in WSL)")

# ---- 3. assemble -------------------------------------------------------------------------
out = ROOT / "dist" / "submission"
if out.exists():
    shutil.rmtree(out)
(out / "figures").mkdir(parents=True)
order = ["figures/fig_pipeline.pdf", "figures/fig_anchors.pdf", "figures/fig_hardware.pdf",
         "figures/fig_countfree.pdf", "figures/fig_validation.pdf", "figures/fig_levelatlas.pdf",
         "figures/fig_fov.pdf"]
# confirm the order against main.tex's includegraphics sequence (Fig. 1 is TikZ, not included)
inc = re.findall(r"includegraphics\[[^\]]*\]\{figures/([a-z_]+)\.pdf\}", src)
assert inc == [Path(p).stem for p in order[1:]], inc
copies = {"main.pdf": "Main_Document_CTSpinoPelvic1K.pdf",
          "title_page.pdf": "Title_Page_CTSpinoPelvic1K.pdf",
          "supplementary.pdf": "Supporting_Information_CTSpinoPelvic1K.pdf"}
for s_, d_ in copies.items():
    shutil.copy(HERE / s_, out / d_)
for k, rel in enumerate(order, 1):
    shutil.copy(HERE / rel, out / "figures" / f"Figure_{k}.pdf")
z = ROOT / "dist" / "CTSpinoPelvic1K_overleaf.zip"
if z.exists():
    shutil.copy(z, out / "LaTeX_source_CTSpinoPelvic1K.zip")
print("assembled:", sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()))
