r"""paper/mpda/make_submission.py -- the upload set for the journal's submission form.

The form wants: the manuscript with figures embedded and captions beneath them AND a list of
figure captions after the references; each figure as its own numbered file; the title page
as a separate item; supporting information separately; and NO abstract in the main document
-- for a Dataset and Software article the structured abstract goes in the form's own box,
from Abstract.txt, and a main document carrying one was returned unreviewed. This script:

  1. writes figure_captions.tex from the \caption{} of every figure in main.tex, in order,
     which main.tex \input{}s after the bibliography when \captionlisttrue (the preprint;
     the ten-page typeset check sets it false so captions are not counted twice);
  2. exports Fig. 1 (drawn in TikZ inside main.tex) as a standalone PDF;
  3. assembles dist/submission/ with the files named as the form expects.

    python paper/mpda/make_submission.py        (after the PDFs are built)
"""
from __future__ import annotations

import re
import sys
try:
    import fitz
except ImportError:
    fitz = None
import shutil
import subprocess
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
src = (HERE / "main.tex").read_text(encoding="utf-8")

# ---- 1. caption list -------------------------------------------------------------------
figs = []
for m in re.finditer(r"\\begin\{figure\*?\}(.*?)\\end\{figure\*?\}", src, re.S):
    body = m.group(1)
    c = re.search(r"\\caption\{", body)
    if not c:
        continue
    # balanced-brace extraction of the caption argument
    i = c.end(); depth = 1
    while depth:
        ch = body[i]; depth += (ch == "{") - (ch == "}"); i += 1
    cap = body[c.end():i - 1]
    cap = re.sub(r"\\label\{[^}]*\}", "", cap).strip()
    figs.append(re.sub(r"\s+", " ", cap))
lines = ["\\section*{Figure captions}", "% generated by make_submission.py; do not edit by hand"]
for k, cap in enumerate(figs, 1):
    lines.append(f"\\noindent\\textbf{{Figure {k}.}} {cap}\n")
(HERE / "figure_captions.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"figure_captions.tex: {len(figs)} captions")

# ---- 2. Fig. 1 standalone ---------------------------------------------------------------
tikz = re.search(r"(\\begin\{tikzpicture\}\[\n  % absolute 8 pt.*?\\end\{tikzpicture\})", src, re.S)
if not tikz:
    tikz = re.search(r"(\\begin\{tikzpicture\}\[.*?\\end\{tikzpicture\})", src, re.S)
standalone = r"""\documentclass[border=2pt]{standalone}
\usepackage{helvet}\renewcommand{\familydefault}{\sfdefault}
\usepackage{tikz}
\usetikzlibrary{arrows.meta, positioning, fit, backgrounds, calc}
\begin{document}
\linespread{1}\selectfont
""" + tikz.group(1) + "\n\\end{document}\n"
(HERE / "fig_pipeline_standalone.tex").write_text(standalone, encoding="utf-8")
print("fig_pipeline_standalone.tex written")
# Figure 1 is the TikZ chart inside main.tex, so this .tex is rewritten on every run --
# but the PDF was NOT recompiled, and the packet shipped a render from before the chart
# was redrawn. Compile it here and let it overwrite figures/fig_pipeline.pdf below.
_sh = ("export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH; "
       "cd /tmp && rm -rf figstand && mkdir figstand && cd figstand && "
       "cp {t} . && pdflatex -interaction=nonstopmode fig_pipeline_standalone.tex >/dev/null 2>&1 "
       "&& cp fig_pipeline_standalone.pdf {o}")
_t = "/mnt/" + str(HERE / "fig_pipeline_standalone.tex").replace(":", "").replace("\\", "/")
_o = "/mnt/" + str(HERE / "figures" / "fig_pipeline.pdf").replace(":", "").replace("\\", "/")
_t = _t[:5] + _t[5].lower() + _t[6:]
_o = _o[:5] + _o[5].lower() + _o[6:]
_r = subprocess.run(["wsl", "-e", "bash", "-lc", _sh.format(t=_t, o=_o)],
                    capture_output=True, text=True)
if _r.returncode:
    raise SystemExit("Figure 1 failed to compile: " + (_r.stderr or _r.stdout)[:400])
print("Figure 1 recompiled ->", (HERE / "figures" / "fig_pipeline.pdf").stat().st_size, "bytes")

# ---- 3. assemble -------------------------------------------------------------------------
out = ROOT / "dist" / "submission"
# Overwrite in place rather than rmtree: a PDF open in a viewer makes the delete fail on
# Windows, and a half-deleted packet is worse than a stale file. Anything the build writes
# is replaced; anything it no longer produces is reported below.
out.mkdir(parents=True, exist_ok=True)
_before = {p.name for p in out.iterdir() if p.is_file()}
# Numbered figures are whatever main.tex actually includes, read off the source rather
# than listed here -- a hard-coded list breaks the moment a figure moves to supporting
# information, which is how the ten-page limit was met. Fig. 1 is TikZ and is not included.
inc = re.findall(r"includegraphics\[[^\]]*\]\{figures/([a-z_]+)\.pdf\}", src)
order = ["figures/fig_pipeline.pdf"] + ["figures/%s.pdf" % f for f in inc]
# figures built but no longer numbered in the main text ship as supporting information
ALL_FIGS = ["fig_anchors", "fig_hardware", "fig_validation", "fig_levelatlas", "fig_fov"]
si_figs = [f for f in ALL_FIGS if f not in inc]
print("main text figures: %s" % ", ".join(["fig_pipeline"] + inc))
print("supporting figures: %s" % (", ".join(si_figs) if si_figs else "(none)"))
# build.sh writes CTSpinoPelvic1K_dataset_article.pdf, NOT main.pdf. Copying main.pdf
# shipped whatever the previous hand-copy left there, one build behind the source.
# MPDA DOES allow supplementary material, and it does not count against the ten published
# pages. supplementary.pdf therefore ships, and main.tex may reference Fig. Sn / Table Sn --
# but every such reference must resolve to something the supplement actually contains.
copies = {"CTSpinoPelvic1K_dataset_article.pdf": "Main_Document_CTSpinoPelvic1K.pdf",
          "title_page.pdf": "Title_Page_CTSpinoPelvic1K.pdf",
          }
# The journal takes supporting information as separately numbered uploads, so the
# combined PDF above is a convenience copy and these are what get attached.
# Routed through wsl for the same reason the Fig. 1 export is: pdflatex is TinyTeX
# inside WSL, and this script runs from Windows.
_ss = "/mnt/" + str(HERE / "make_supplemental_files.py").replace(":", "").replace("\\", "/")
_ss = _ss[:5] + _ss[5].lower() + _ss[6:]
_rs = subprocess.run(
    ["wsl", "-e", "bash", "-lc",
     "export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH; python3 " + _ss],
    capture_output=True, text=True)
print(_rs.stdout.strip())

# the abstract as plain text for the form's paste box; written here because the directory
# is rebuilt on every run and a file dropped in by hand would not survive
_ab = "/mnt/" + str(HERE / "make_abstract_text.py").replace(":", "").replace(chr(92), "/")
_ab = _ab[:5] + _ab[5].lower() + _ab[6:]
_ra = subprocess.run(["wsl", "-e", "bash", "-lc", "python3 " + _ab],
                     capture_output=True, text=True)
if _ra.returncode != 0:
    raise SystemExit("abstract extraction failed:" + _ra.stdout[-400:] + _ra.stderr[-400:])
print([l for l in _ra.stdout.splitlines() if "words" in l][-1])
if _rs.returncode != 0:
    raise SystemExit("supplemental build failed:\n" + _rs.stdout[-800:] + _rs.stderr[-800:])
refs = set(re.findall(r"(?:Fig\.|Figure|Table)~(S\d+)", src))
sup_pdf = fitz.open(str(HERE / "supplementary.pdf")) if fitz else None
if sup_pdf is not None:
    sup_txt = "".join(p.get_text() for p in sup_pdf)
    for r in sorted(refs):
        kind = "FIG" if r.startswith("S") else ""
        if r not in sup_txt.replace(" ", ""):
            raise SystemExit("main.tex cites %s but supplementary.pdf does not contain it" % r)
    print("supplementary references resolved: %s" % (", ".join(sorted(refs)) or "(none)"))

# The main document is written by build.sh, not here, so a packet assembled before a
# rebuild would ship the returned version with its abstract. Read the PDF and refuse.
if fitz is None:
    raise SystemExit("pymupdf is needed to check the main document for an abstract")
_mt = " ".join(p.get_text() for p in fitz.open(str(HERE / "CTSpinoPelvic1K_dataset_article.pdf")))
_mt = re.sub(r"\s+", " ", _mt)
for _mark in ("Purpose:", "Data Format and Usage Notes:", "Potential Applications:"):
    if _mark in _mt:
        raise SystemExit("the main document PDF still carries the abstract (%r) -- run "
                         "build.sh first" % _mark)
print("main document: no abstract (it goes in the form, from Abstract.txt)")

for s_, d_ in copies.items():
    shutil.copy(HERE / s_, out / d_)
for k, rel in enumerate(order, 1):
    shutil.copy(HERE / rel, out / f"Figure_{k}.pdf")
if si_figs:
    print("carried in supplementary.pdf, not as numbered main figures: %s" % ", ".join(si_figs))
# the Overleaf project: sources, the six included figures (Fig. 1 is TikZ inside main.tex),
# the caption list, and the README that says how to set the main document
# supplementary.tex \input{}s supplement_body.tex and includes the supporting figures; the
# zip once shipped it without either, so it could not compile in Overleaf.
z = ROOT / "dist" / "CTSpinoPelvic1K_overleaf.zip"
with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
    for name in ["main.tex", "title_page.tex", "supplementary.tex", "supplement_body.tex",
                 "census_table.tex", "figure_captions.tex"]:
        zf.write(HERE / name, name)
    zf.write(HERE / "overleaf_README.md", "README.md")
    for rel in order[1:] + ["figures/%s.pdf" % f for f in si_figs]:
        zf.write(HERE / rel, rel)
_zn = set(zipfile.ZipFile(z).namelist())
for _tex in ("main.tex", "supplementary.tex", "supplement_body.tex"):
    _t = (HERE / _tex).read_text(encoding="utf-8")
    _need = set(re.findall(r"\{(figures/[A-Za-z0-9_]+\.pdf)\}", _t))
    _need |= {n + ".tex" for n in re.findall(r"\\input\{([A-Za-z0-9_]+)\}", _t)}
    if _need - _zn:
        raise SystemExit("Overleaf zip is missing what %s needs: %s" % (_tex, sorted(_need - _zn)))
print("Overleaf project: %d files, every input and figure present" % len(_zn))

# THE SUBMITTED ZIP IS NOT THE OVERLEAF PROJECT. The journal's length estimator compiles
# the .tex files it finds, and a fragment is not a document: census_table.tex opens with a
# table environment and no preamble, so the estimator failed on it with "Environment table
# undefined". The submission gets ONE self-contained main.tex and its figures, so there is
# nothing else that can be compiled by mistake.
_src = (HERE / "main.tex").read_text(encoding="utf-8")
_caps = (HERE / "figure_captions.tex").read_text(encoding="utf-8")
_hook = "\\ifcaptionlist\\input{figure_captions}\\fi"
if _hook not in _src:
    raise SystemExit("caption-list hook not found in main.tex")
_src = _src.replace(_hook, "\\ifcaptionlist\n" + _caps.rstrip() + "\n\\fi")
_a = _src.find(chr(92) + "ifsupplement" + chr(10) + chr(92) + "clearpage")
if _a != -1:
    _b = _src.find("\\fi", _src.find("\\input{supplement_body}", _a))
    _src = _src[:_a] + _src[_b + 3:]
if "\\input{" in _src:
    raise SystemExit("submitted main.tex still has an input: "
                     + _src[_src.find("\\input{"):][:60])
# NO ABSTRACT. \abstractfalse already keeps it off the page; it is cut from the submitted
# source too, so an editor opening the .tex does not find the text they asked to remove.
_open, _close = "\\ifabstract\n\\begin{abstract}", "\\end{abstract}\n\\fi"
_a = _src.find(_open)
if _a == -1 or _src.find(_close, _a) == -1:
    raise SystemExit("abstract block not found in main.tex -- expected it behind \\ifabstract")
_src = _src[:_a] + _src[_src.find(_close, _a) + len(_close):]
if "\\begin{abstract}" in _src:
    raise SystemExit("submitted main.tex still carries an abstract")

# NO ZIP: THE SOURCE SITS LOOSE IN THE PACKET. The estimator flattens the upload, so a
# figures/ directory is lost and every \includegraphics fails with "File not found: using
# draft setting". The .tex therefore names each figure as its upload is named (Figure_2.pdf,
# ...), and those files are already beside it in this folder, so it compiles where it is.
# Fig. 1 is TikZ inside the .tex and needs no file.
for k, rel in enumerate(order[1:], 2):
    if "{%s}" % rel not in _src:
        raise SystemExit("submitted main.tex does not include %s" % rel)
    _src = _src.replace("{%s}" % rel, "{Figure_%d.pdf}" % k)
if "{figures/" in _src:
    raise SystemExit("submitted main.tex still names a figures/ path: "
                     + _src[_src.find("{figures/"):][:60])
(out / "Main_Document_CTSpinoPelvic1K.tex").write_text(_src, encoding="utf-8", newline="\n")
for _old in (out / "LaTeX_source_CTSpinoPelvic1K.zip",
             ROOT / "dist" / "CTSpinoPelvic1K_submitted_source.zip"):
    if _old.exists():
        _old.unlink()
print("submitted source: Main_Document_CTSpinoPelvic1K.tex, using %s from this folder"
      % ", ".join("Figure_%d.pdf" % k for k in range(2, len(order) + 1)))
shutil.copy(HERE / "cover_letter.md", out / "Cover_Letter.md")
_after = {p.name for p in out.iterdir() if p.is_file()}
_stale = sorted(_before - _after)
if _stale:
    print("STALE, not produced by this build:", ", ".join(_stale))
print("assembled:", sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()))
