r"""paper/mpda/make_submission.py -- the upload set for the journal's submission form.

The form wants: the manuscript with figures embedded and captions beneath them AND a list of
figure captions after the references; each figure as its own numbered file; the title page
as a separate item; the supporting information as ONE separate document; and NO abstract in
the main document -- for a Dataset and Software article the structured abstract goes in the
form's own box, from Abstract.txt, and a main document carrying one was returned unreviewed.

ONE SUPPORTING INFORMATION DOCUMENT. The 2026-09-21 packet uploaded the supplement as six
files titled "Supplemental Material 1..6" while the article cites Fig. S1-S3 and Table
S1-S3 and listed the six items, one line each, in a Supporting Information section. The
editorial office read that list as the items themselves and the inventory as S1-S6: "Kindly
provide all supplementary figures and tables in the correct sequential order." One document,
Figure S1, S2, S3 then Table S1, S2, S3, numbered as the text cites them, and a main
document that carries no supplementary figure, table or caption. This script:

  1. writes figure_captions.tex from the \caption{} of every figure in main.tex, in order,
     which main.tex \input{}s after the bibliography when \captionlisttrue (the preprint;
     the ten-page typeset check sets it false so captions are not counted twice);
  2. exports Fig. 1 (drawn in TikZ inside main.tex) as a standalone PDF;
  3. builds supplementary.pdf and title_page.pdf, so neither can be older than its source;
  4. checks the supplement carries the six items in that order under the labels the text
     cites, and that the main document carries none of them and no abstract;
  5. assembles dist/submission/ with the files named as the form expects.

    python paper/mpda/make_submission.py        (after the PDFs are built)
"""
from __future__ import annotations

import re
import sys
try:
    import fitz
except ImportError:
    fitz = None
import shutil
import subprocess
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
src = (HERE / "main.tex").read_text(encoding="utf-8")

# ---- 1. caption list -------------------------------------------------------------------
figs = []
for m in re.finditer(r"\\begin\{figure\*?\}(.*?)\\end\{figure\*?\}", src, re.S):
    body = m.group(1)
    c = re.search(r"\\caption\{", body)
    if not c:
        continue
    # balanced-brace extraction of the caption argument
    i = c.end(); depth = 1
    while depth:
        ch = body[i]; depth += (ch == "{") - (ch == "}"); i += 1
    cap = body[c.end():i - 1]
    cap = re.sub(r"\\label\{[^}]*\}", "", cap).strip()
    figs.append(re.sub(r"\s+", " ", cap))
lines = ["\\section*{Figure captions}", "% generated by make_submission.py; do not edit by hand"]
for k, cap in enumerate(figs, 1):
    lines.append(f"\\noindent\\textbf{{Figure {k}.}} {cap}\n")
(HERE / "figure_captions.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"figure_captions.tex: {len(figs)} captions")

# ---- 2. Fig. 1 standalone ---------------------------------------------------------------
tikz = re.search(r"(\\begin\{tikzpicture\}\[\n  % absolute 8 pt.*?\\end\{tikzpicture\})", src, re.S)
if not tikz:
    tikz = re.search(r"(\\begin\{tikzpicture\}\[.*?\\end\{tikzpicture\})", src, re.S)
standalone = r"""\documentclass[border=2pt]{standalone}
\usepackage{helvet}\renewcommand{\familydefault}{\sfdefault}
\usepackage{tikz}
\usetikzlibrary{arrows.meta, positioning, fit, backgrounds, calc}
\begin{document}
\linespread{1}\selectfont
""" + tikz.group(1) + "\n\\end{document}\n"
(HERE / "fig_pipeline_standalone.tex").write_text(standalone, encoding="utf-8")
print("fig_pipeline_standalone.tex written")
# Figure 1 is the TikZ chart inside main.tex, so this .tex is rewritten on every run --
# but the PDF was NOT recompiled, and the packet shipped a render from before the chart
# was redrawn. Compile it here and let it overwrite figures/fig_pipeline.pdf below.
_sh = ("export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH; "
       "cd /tmp && rm -rf figstand && mkdir figstand && cd figstand && "
       "cp {t} . && pdflatex -interaction=nonstopmode fig_pipeline_standalone.tex >/dev/null 2>&1 "
       "&& cp fig_pipeline_standalone.pdf {o}")
_t = "/mnt/" + str(HERE / "fig_pipeline_standalone.tex").replace(":", "").replace("\\", "/")
_o = "/mnt/" + str(HERE / "figures" / "fig_pipeline.pdf").replace(":", "").replace("\\", "/")
_t = _t[:5] + _t[5].lower() + _t[6:]
_o = _o[:5] + _o[5].lower() + _o[6:]
_r = subprocess.run(["wsl", "-e", "bash", "-lc", _sh.format(t=_t, o=_o)],
                    capture_output=True, text=True)
if _r.returncode:
    raise SystemExit("Figure 1 failed to compile: " + (_r.stderr or _r.stdout)[:400])
print("Figure 1 recompiled ->", (HERE / "figures" / "fig_pipeline.pdf").stat().st_size, "bytes")

# ---- 3. assemble -------------------------------------------------------------------------
out = ROOT / "dist" / "submission"
# Overwrite in place rather than rmtree: a PDF open in a viewer makes the delete fail on
# Windows, and a half-deleted packet is worse than a stale file. Anything the build writes
# is replaced; anything it no longer produces is reported below.
out.mkdir(parents=True, exist_ok=True)
# The six split files must not be uploaded again; remove them rather than report them stale.
for _p in sorted(out.glob("Supplemental_Material_*.pdf")):
    _p.unlink()
    print("removed", _p.name, "(superseded by Supporting_Information_CTSpinoPelvic1K.pdf)")
_before = {p.name for p in out.iterdir() if p.is_file()}
# Numbered figures are whatever main.tex actually includes, read off the source rather
# than listed here -- a hard-coded list breaks the moment a figure moves to supporting
# information, which is how the ten-page limit was met. Fig. 1 is TikZ and is not included.
inc = re.findall(r"includegraphics\[[^\]]*\]\{figures/([a-z_]+)\.pdf\}", src)
order = ["figures/fig_pipeline.pdf"] + ["figures/%s.pdf" % f for f in inc]
# figures built but no longer numbered in the main text ship as supporting information
ALL_FIGS = ["fig_anchors", "fig_hardware", "fig_validation", "fig_levelatlas", "fig_fov"]
si_figs = [f for f in ALL_FIGS if f not in inc]
print("main text figures: %s" % ", ".join(["fig_pipeline"] + inc))
print("supporting figures: %s" % (", ".join(si_figs) if si_figs else "(none)"))
# build.sh writes CTSpinoPelvic1K_dataset_article.pdf, NOT main.pdf. Copying main.pdf
# shipped whatever the previous hand-copy left there, one build behind the source.
# MPDA DOES allow supplementary material, and it does not count against the ten published
# pages. supplementary.pdf ships as the one Supporting Information document, and main.tex
# may reference Fig. Sn / Table Sn -- but every such reference must resolve to something
# the supplement actually contains, under that label.
copies = {"CTSpinoPelvic1K_dataset_article.pdf": "Main_Document_CTSpinoPelvic1K.pdf",
          "title_page.pdf": "Title_Page_CTSpinoPelvic1K.pdf",
          "supplementary.pdf": "Supporting_Information_CTSpinoPelvic1K.pdf",
          }
# Both built here, in WSL like the Fig. 1 export: pdflatex is TinyTeX inside WSL and this
# script runs from Windows. supplementary.pdf was last built by hand on 2026-09-19 and
# title_page.pdf the same day; a packet must not ship a PDF older than its .tex.
_d = "/mnt/" + str(HERE).replace(":", "").replace("\\", "/")
_d = _d[:5] + _d[5].lower() + _d[6:]


def _wsl_pdflatex(stem, extra):
    sh = ("export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH; "
          "rm -rf /tmp/mpda_{s} && mkdir -p /tmp/mpda_{s}/figures && cd /tmp/mpda_{s} && "
          "cp {d}/{s}.tex . && {x} "
          "pdflatex -interaction=nonstopmode {s}.tex >/dev/null 2>&1; "
          "pdflatex -interaction=nonstopmode {s}.tex >/dev/null 2>&1; "
          "cp {s}.log {d}/{s}.log; cp {s}.pdf {d}/{s}.pdf").format(s=stem, d=_d, x=extra)
    r = subprocess.run(["wsl", "-e", "bash", "-lc", sh], capture_output=True, text=True)
    log = (HERE / (stem + ".log")).read_text(encoding="utf-8", errors="replace")
    bad = [l for l in log.splitlines()
           if l.startswith("!") or re.search(r"(Reference|Citation) `[^']*' .*undefined", l)]
    if r.returncode or bad or not (HERE / (stem + ".pdf")).exists():
        raise SystemExit("%s.tex failed to build: %s" % (stem, bad[0] if bad else (r.stderr or r.stdout)[-400:]))
    print("%s.pdf rebuilt from source" % stem)


_wsl_pdflatex("supplementary",
              "cp {d}/supplement_body.tex {d}/census_table.tex . && cp {d}/figures/*.pdf figures/ &&".format(d=_d))
_wsl_pdflatex("title_page", "")

# the abstract as plain text for the form's paste box; written here because the directory
# is rebuilt on every run and a file dropped in by hand would not survive
_ab = "/mnt/" + str(HERE / "make_abstract_text.py").replace(":", "").replace(chr(92), "/")
_ab = _ab[:5] + _ab[5].lower() + _ab[6:]
_ra = subprocess.run(["wsl", "-e", "bash", "-lc", "python3 " + _ab],
                     capture_output=True, text=True)
if _ra.returncode != 0:
    raise SystemExit("abstract extraction failed:" + _ra.stdout[-400:] + _ra.stderr[-400:])
print([l for l in _ra.stdout.splitlines() if "words" in l][-1])
if fitz is None:
    raise SystemExit("pymupdf is needed to check the packet")
# THE SIX ITEMS, IN ORDER, UNDER THE LABELS THE TEXT CITES. Read the rendered supplement,
# not the source: the combined supplement once compiled cleanly with all three figures
# missing. Each caption is located by its label plus its own first words, because a
# cross-reference inside a caption ("in Table S3") would otherwise be taken for the caption.
_sup = re.sub(r"\s+", " ", " ".join(p.get_text() for p in fitz.open(str(HERE / "supplementary.pdf"))))
_body = (HERE / "supplement_body.tex").read_text(encoding="utf-8")
_body = _body.replace("\\input{census_table}", (HERE / "census_table.tex").read_text(encoding="utf-8"))
_items, _nf, _nt = [], 0, 0
for _m in re.finditer(r"\\begin\{(figure|table)\*?\}(.*?)\\end\{\1\*?\}", _body, re.S):
    _c = re.search(r"\\caption\{(.*)", _m.group(2), re.S).group(1)
    _c = re.sub(r"\\label\{[^}]*\}", "", _c)
    _first = " ".join(re.findall(r"[A-Za-z][A-Za-z-]*", _c.split("\\")[0].split("$")[0])[:4])
    if _m.group(1) == "figure":
        _nf += 1; _items.append(("Figure S%d" % _nf, _first))
    else:
        _nt += 1; _items.append(("Table S%d" % _nt, _first))
_pos = []
for _lab, _first in _items:
    _hit = re.search(re.escape(_lab) + r"\.?\s+" + re.escape(_first).replace(r"\ ", r"\s*"), _sup)
    if not _hit:
        raise SystemExit("supplementary.pdf does not carry %s (%r)" % (_lab, _first))
    _pos.append(_hit.start())
if _pos != sorted(_pos):
    raise SystemExit("supplementary items are out of order: %s" % [l for l, _ in _items])
print("supporting information: %s, in that order" % ", ".join(l for l, _ in _items))
for _kind, _num in set(re.findall(r"(Fig\.|Figure|Table)~(S\d+)", src)):
    _lab = ("Table " if _kind == "Table" else "Figure ") + _num
    if _lab not in [l for l, _ in _items]:
        raise SystemExit("main.tex cites %s %s but the supplement has no %s" % (_kind, _num, _lab))
print("supplementary references resolved: %s" % ", ".join(sorted(set(
    "%s %s" % kn for kn in re.findall(r"(Fig\.|Figure|Table)~(S\d+)", src)))))

# The main document is written by build.sh, not here, so a packet assembled before a
# rebuild would ship the returned version with its abstract. Read the PDF and refuse.
if fitz is None:
    raise SystemExit("pymupdf is needed to check the main document for an abstract")
_mt = " ".join(p.get_text() for p in fitz.open(str(HERE / "CTSpinoPelvic1K_dataset_article.pdf")))
_mt = re.sub(r"\s+", " ", _mt)
for _mark in ("Purpose:", "Data Format and Usage Notes:", "Potential Applications:"):
    if _mark in _mt:
        raise SystemExit("the main document PDF still carries the abstract (%r) -- run "
                         "build.sh first" % _mark)
print("main document: no abstract (it goes in the form, from Abstract.txt)")
# ... AND NO SUPPLEMENTARY ITEM. Neither a caption from the supplement, nor the split files'
# title, nor the one-line-per-item list the office read as the items themselves.
for _lab, _first in _items:
    if re.search(re.escape(_first).replace(r"\ ", r"\s*"), _mt):
        raise SystemExit("the main document carries the caption of %s (%r)" % (_lab, _first))
for _mark in ("Supplemental Material", "Fig. S1, the", "Table S1, the"):
    if _mark in _mt:
        raise SystemExit("the main document still carries supplementary material (%r)" % _mark)
print("main document: no supplementary figure, table or caption")

for s_, d_ in copies.items():
    shutil.copy(HERE / s_, out / d_)
for k, rel in enumerate(order, 1):
    shutil.copy(HERE / rel, out / f"Figure_{k}.pdf")
if si_figs:
    print("carried in supplementary.pdf, not as numbered main figures: %s" % ", ".join(si_figs))
# the Overleaf project: sources, the six included figures (Fig. 1 is TikZ inside main.tex),
# the caption list, and the README that says how to set the main document
# supplementary.tex \input{}s supplement_body.tex and includes the supporting figures; the
# zip once shipped it without either, so it could not compile in Overleaf.
z = ROOT / "dist" / "CTSpinoPelvic1K_overleaf.zip"
with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
    for name in ["main.tex", "title_page.tex", "supplementary.tex", "supplement_body.tex",
                 "census_table.tex", "figure_captions.tex"]:
        zf.write(HERE / name, name)
    zf.write(HERE / "overleaf_README.md", "README.md")
    for rel in order[1:] + ["figures/%s.pdf" % f for f in si_figs]:
        zf.write(HERE / rel, rel)
_zn = set(zipfile.ZipFile(z).namelist())
for _tex in ("main.tex", "supplementary.tex", "supplement_body.tex"):
    _t = (HERE / _tex).read_text(encoding="utf-8")
    _need = set(re.findall(r"\{(figures/[A-Za-z0-9_]+\.pdf)\}", _t))
    _need |= {n + ".tex" for n in re.findall(r"\\input\{([A-Za-z0-9_]+)\}", _t)}
    if _need - _zn:
        raise SystemExit("Overleaf zip is missing what %s needs: %s" % (_tex, sorted(_need - _zn)))
print("Overleaf project: %d files, every input and figure present" % len(_zn))

# THE SUBMITTED ZIP IS NOT THE OVERLEAF PROJECT. The journal's length estimator compiles
# the .tex files it finds, and a fragment is not a document: census_table.tex opens with a
# table environment and no preamble, so the estimator failed on it with "Environment table
# undefined". The submission gets ONE self-contained main.tex and its figures, so there is
# nothing else that can be compiled by mistake.
_src = (HERE / "main.tex").read_text(encoding="utf-8")
_caps = (HERE / "figure_captions.tex").read_text(encoding="utf-8")
_hook = "\\ifcaptionlist\\input{figure_captions}\\fi"
if _hook not in _src:
    raise SystemExit("caption-list hook not found in main.tex")
_src = _src.replace(_hook, "\\ifcaptionlist\n" + _caps.rstrip() + "\n\\fi")
_a = _src.find(chr(92) + "ifsupplement" + chr(10) + chr(92) + "clearpage")
if _a != -1:
    _b = _src.find("\\fi", _src.find("\\input{supplement_body}", _a))
    _src = _src[:_a] + _src[_b + 3:]
if "\\input{" in _src:
    raise SystemExit("submitted main.tex still has an input: "
                     + _src[_src.find("\\input{"):][:60])
# NO ABSTRACT. \abstractfalse already keeps it off the page; it is cut from the submitted
# source too, so an editor opening the .tex does not find the text they asked to remove.
_open, _close = "\\ifabstract\n\\begin{abstract}", "\\end{abstract}\n\\fi"
_a = _src.find(_open)
if _a == -1 or _src.find(_close, _a) == -1:
    raise SystemExit("abstract block not found in main.tex -- expected it behind \\ifabstract")
_src = _src[:_a] + _src[_src.find(_close, _a) + len(_close):]
if "\\begin{abstract}" in _src:
    raise SystemExit("submitted main.tex still carries an abstract")

# NO ZIP: THE SOURCE SITS LOOSE IN THE PACKET. The estimator flattens the upload, so a
# figures/ directory is lost and every \includegraphics fails with "File not found: using
# draft setting". The .tex therefore names each figure as its upload is named (Figure_2.pdf,
# ...), and those files are already beside it in this folder, so it compiles where it is.
# Fig. 1 is TikZ inside the .tex and needs no file.
for k, rel in enumerate(order[1:], 2):
    if "{%s}" % rel not in _src:
        raise SystemExit("submitted main.tex does not include %s" % rel)
    _src = _src.replace("{%s}" % rel, "{Figure_%d.pdf}" % k)
if "{figures/" in _src:
    raise SystemExit("submitted main.tex still names a figures/ path: "
                     + _src[_src.find("{figures/"):][:60])
(out / "Main_Document_CTSpinoPelvic1K.tex").write_text(_src, encoding="utf-8", newline="\n")
for _old in (out / "LaTeX_source_CTSpinoPelvic1K.zip",
             ROOT / "dist" / "CTSpinoPelvic1K_submitted_source.zip"):
    if _old.exists():
        _old.unlink()
print("submitted source: Main_Document_CTSpinoPelvic1K.tex, using %s from this folder"
      % ", ".join("Figure_%d.pdf" % k for k in range(2, len(order) + 1)))
shutil.copy(HERE / "cover_letter.md", out / "Cover_Letter.md")
_after = {p.name for p in out.iterdir() if p.is_file()}
_stale = sorted(_before - _after)
if _stale:
    print("STALE, not produced by this build:", ", ".join(_stale))
print("assembled:", sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()))
